version: "3.7"

services:
  web:
    image: pxsocs/node_warden:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "$APP_BTC_RPC_EXPLORER_PORT:$APP_BTC_RPC_EXPLORER_PORT"

    tty: true

    environment:
      # Docker requirements
      BTCEXP_HOST: 0.0.0.0
      # Bitcoin Core
      BTCEXP_BITCOIN_NETWORK: $BITCOIN_NETWORK
      BTCEXP_BITCOIND_HOST: $BITCOIN_IP
      BTCEXP_BITCOIND_PORT: $BITCOIN_RPC_PORT
      BTCEXP_BITCOIND_USER: $BITCOIN_RPC_USER
      BTCEXP_BITCOIND_PASS: $BITCOIN_RPC_PASS
      # Electrum
      BTCEXP_ADDRESS_API: electrumx
      BTCEXP_ELECTRUMX_SERVERS: "tcp://$ELECTRUM_IP:$ELECTRUM_PORT"
      # Log level
      DEBUG: "btcexp:*,electrumClient"
      # Performance
      BTCEXP_SLOW_DEVICE_MODE: "true"
      BTCEXP_NO_INMEMORY_RPC_CACHE: "true"
      # Privacy
      BTCEXP_PRIVACY_MODE: "true"
      BTCEXP_NO_RATES: "true"
      # Disable RPC
      BTCEXP_RPC_ALLOWALL: "false"
      BTCEXP_BASIC_AUTH_PASSWORD: ""
      # Tor proxy environment variables
      TOR_PROXY_IP: $TOR_PROXY_IP
      TOR_PROXY_PORT: $TOR_PROXY_PORT

    networks:
      default:
